#
# Travis CI configuration file
#
# ICRAR - International Centre for Radio Astronomy Research
# (c) UWA - The University of Western Australia, 2018
# Copyright by UWA (in the framework of the ICRAR)
# All rights reserved
#
# Contributed by Rodrigo Tobar
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307  USA
#

language: cpp
sudo: false

# We try with both GNU and LLVM
# When running with gcc-6 we also collect coverage information
# and upload it to coveralls
matrix:
 include:
  - compiler: gcc
    dist: xenial
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-5, libhdf5-dev, hdf5-tools, libboost-filesystem-dev, libboost-program-options-dev, libboost-log-dev, cxxtest, libgsl-dev]
    env: COMPILER=g++-5
  - compiler: gcc
    dist: xenial
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-6, libhdf5-dev, hdf5-tools, libboost-filesystem-dev, libboost-program-options-dev, libboost-log-dev, cxxtest, libgsl-dev, python-matplotlib, python-scipy, python-h5py, python-tk]
    env: COMPILER=g++-6 PYTHON=python
  - compiler: gcc
    dist: xenial
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-7, libhdf5-dev, hdf5-tools, libboost-filesystem-dev, libboost-program-options-dev, libboost-log-dev, cxxtest, libgsl-dev, python3-matplotlib, python3-scipy, python3-h5py, python3-tk]
    env: COMPILER=g++-7 PYTHON=python3
  - compiler: clang
    dist: xenial
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-7, libhdf5-dev, hdf5-tools, libboost-filesystem-dev, libboost-program-options-dev, libboost-log-dev, cxxtest, libgsl-dev]
    env: COMPILER=clang++ LD_LIBRARY_PATH=/usr/local/clang-7.0.0/lib
  - os: osx
    osx_image: xcode12.2 # OSX 10.15.7
    env: COMPILER=clang++ PYTHON=venv
  - os: osx
    osx_image: xcode13.1  # OSX 11.6
    env: COMPILER=clang++
  - os: osx
    osx_image: xcode13.3  # OSX 12.3
    env: COMPILER=clang++

# We "source" it because it exports variables
before_install:
 - source .travis/before_install.sh

install:
 - source .travis/install.sh

script:
 - source .travis/test.sh
